# Generated by Django 3.0.7 on 2020-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
